name: "gs4d-spline"
tag: "${data.random_camera.height}_${rmspace:${basename:${data.video_frames_dir}},_}"
exp_root_dir: "outputs"
seed: 0

data_type: "temporal-image-datamodule"
data: # threestudio/data/image.py -> SingleImageDataModuleConfig
  video_frames_dir: ./load/videos/anya2
  norm_timestamp: true
  num_frames: 10
  height: [256, 512]
  width: [256, 512]
  resolution_milestones: [100]
  default_elevation_deg: 5.0
  default_azimuth_deg: 0.0
  default_camera_distance: 3.8
  default_fovy_deg: 20.0
  requires_depth: ${cmaxgt0orcmaxgt0:${system.loss.lambda_depth},${system.loss.lambda_depth_rel}}
  requires_normal: ${cmaxgt0:${system.loss.lambda_normal}}
  random_camera: # threestudio/data/uncond.py -> RandomCameraDataModuleConfig
    height: 256
    width: 256
    batch_size: 2
    eval_height: 512
    eval_width: 512
    eval_batch_size: 1
    elevation_range: [-10, 80]
    azimuth_range: [-180, 180]
    camera_distance_range: [3.8, 3.8]
    fovy_range: [20.0, 20.0] # Zero123 has fixed fovy
    progressive_until: 0
    camera_perturb: 0.0
    center_perturb: 0.0
    up_perturb: 0.0
    light_position_perturb: 1.0
    light_distance_range: [7.5, 10.0]
    eval_elevation_deg: ${data.default_elevation_deg}
    eval_camera_distance: ${data.default_camera_distance}
    eval_fovy_deg: ${data.default_fovy_deg}
    light_sample_strategy: "dreamfusion"
    batch_uniform_azimuth: False
    n_val_views: 30
    n_test_views: 120

system_type: "gaussian-splatting-4dgen-system"
system:
  stage: motion

  geometry_type: "spacetime-gaussian-splatting"
  geometry:
    use_spline: true
    num_frames: 12

    enable_static: false
    position_lr: 0.001
    scale_lr: 0.001
    feature_lr: 0.01
    opacity_lr: 0.05
    rotation_lr: 0.001
    densification_interval: 1000
    prune_interval: 1000
    opacity_reset_interval: 100000
    densify_from_iter: ${trainer.max_steps}
    densify_until_iter: ${trainer.max_steps}
    prune_from_iter: ${trainer.max_steps}
    prune_until_iter: ${trainer.max_steps}
    densify_grad_threshold: 0.01
    min_opac_prune: 0.005
    split_thresh: 0.02
    radii2d_thresh: 1000

    enable_dynamic: true
    delta_xyz_lr: 0.001
    delta_rot_lr: 0.0001

    enable_spacetime: false
    omega_lr: 0.0001
    trbfc_lr: 0.0001
    trbfs_lr: 0.03
    move_lr: 3.5

    rank_motion: 3
    rank_omega: 1
    
    addsphpointsscale: 0.8
    trbfslinit: 0.0
    raystart: 0.7
    spatial_lr_scale: 1

    sphere: False

    init_num_pts: 4096
    pc_init_radius: 0.5
    opacity_init: 0.05
    max_num: 500000

    enable_deformation: false
    deformation_lr: 0.00064
    grid_lr: 0.0064

  exporter_type: "gaussian-mesh-exporter"

  renderer_type: "diff-gaussian-rasterizer-spacetime"
  renderer:
    debug: false
    invert_bg_prob: 1.0

  material_type: "no-material" # unused
  material:
    n_output_dims: 0

  background_type: "solid-color-background" # unused

  prompt_processor_type: "dummy-prompt-processor" # Zero123 doesn't use prompts
  prompt_processor:
    pretrained_model_name_or_path: ""
    prompt: ""

  guidance_zero123_type: "temporal-stable-zero123-guidance"
  guidance_zero123:
    num_frames: ${data.num_frames}
    pretrained_config: "./load/zero123/sd-objaverse-finetune-c_concat-256.yaml"
    pretrained_model_name_or_path: "/home/lzq/workspace/huggingface_models/zero123/stable_zero123.ckpt"
    vram_O: ${not:${gt0:${system.freq.guidance_eval}}}
    cond_video_dir: ${data.video_frames_dir}
    cond_elevation_deg: ${data.default_elevation_deg}
    cond_azimuth_deg: ${data.default_azimuth_deg}
    cond_camera_distance: ${data.default_camera_distance}
    guidance_scale: 3.0
    min_step_percent: 0.1  # (start_iter, start_val, end_val, end_iter)
    max_step_percent: 0.6
    chunk_size: null

  prompt_processor_3d_type: null
  guidance_3d_type: null

  freq:
    ref_only_steps: 0
    guidance_eval: 0
    smooth_reg: 1
    reset_neighbors: 10

  loggers:
    wandb:
      enable: false
      project: "threestudio"
      name: None

  loss:
    lambda_sds: 0.1
    lambda_sds_vid: 0
    lambda_rgb: 10000
    lambda_mask: 10000.
    lambda_depth: 0. # 0.05
    lambda_depth_rel: 0. # [0, 0, 0.05, 100]
    lambda_normal: 0. # [0, 0, 0.05, 100]
    lambda_normal_smooth: 0.
    lambda_3d_normal_smooth: 0.
    lambda_arap_reg: 1000.
    lambda_opacity_binary: 0. # [ 0, 0.1, 0.1, 1500 ]
    lambda_density_regulation: [100, 0, 10, 101]
    lambda_normal_regulation: [100, 0, 1, 101]


  optimizer:
    name: Adam
    args:
      lr: 0.01
      betas: [0.9, 0.99]
      eps: 1.e-8
    params:
      background:
        lr: 0.001

  sugar:
    reset_neighbors_every: ${system.freq.reset_neighbors}
    start_regularization_from: 0 # consistent with lambda_density_regulation
    n_samples_for_sdf_regularization: 50000
    start_sdf_better_normal_from: 0 # consistent with lambda_normal_regulation
    use_sdf_better_normal_loss: true
    prune_hard_opacity_threshold: 0.5
    prune_low_opacity_gaussians_at: null # consistent with lambda opacity binary end
    knn_to_track: 8

trainer:
  max_steps: 5000
  log_every_n_steps: 1
  num_sanity_val_steps: 0
  val_check_interval: 100
  enable_progress_bar: true
  precision: 32

checkpoint:
  save_last: true # save at each validation time
  save_top_k: -1
  every_n_train_steps: 1000 # ${trainer.max_steps}
